apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-onfailure-retry
  name: pod-onfailure-retry
spec:
  containers:
  - image: sysnet4admin/net-tools
    name: net-tools
    command: ["/bin/sh", "-c"]
    args:
    - nslook kubernetes # typo issue
  restartPolicy: OnFailure 

