apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-topologyspreadconstraints
  name: eks-topologyspreadconstraints
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-topologyspreadconstraints
  template:
    metadata:
      labels:
        app: eks-topologyspreadconstraints
    spec:
      containers:
      - image: nginx
        name: nginx
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: failure-domain.beta.kubernetes.io/region
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: eks-topologyspreadconstraints
      - maxSkew: 1
        topologyKey: failure-domain.beta.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: eks-topologyspreadconstraints
