apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: limits-3g-pvc-failure
  namespace: dev2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: managed-nfs-storage 
