apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: limits-1g-pvc
  namespace: dev2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage 
