apiVersion: v1
kind: Pod
metadata:
  labels:
    run: liveness-tcpsocket
  name: liveness-tcpsocket
spec:
  containers:
  - name: healthz-nginx 
    image: sysnet4admin/healthz-nginx 
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
