apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logs
  name: logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
      - image: nginx
        name: nginx
