apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-command
  name: simple-command 
spec:
  containers:
  - image: sysnet4admin/net-tools
    name: net-tools
    command: ["/bin/sh", "-c", "sleep 3600"]

