apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quota-3g-pvc-failure  
  namespace: dev1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: managed-nfs-storage 
