apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quota-1g-pvc1  
  namespace: dev1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage 
