apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-tmp
  labels:
    app: hostpath-tmp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostpath-tmp
  template:
    metadata:
      labels:
        app: hostpath-tmp
    spec:
      serviceAccountName: psp-sa
      containers:
      - name: host-mon
        image: sysnet4admin/sleepy
        volumeMounts:
        - mountPath: /host-log
          name: hostpath-directory
      volumes:
      - name: hostpath-directory
        hostPath:
          path: /tmp
