apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy12-load-w3
  name: deploy12-load-w3
spec:
  replicas: 12
  selector:
    matchLabels:
      app: deploy12-load-w3
  template:
    metadata:
      labels:
        app: deploy12-load-w3
    spec:
      containers:
      - name: nginx
        image: nginx
      nodeName: w3-k8s
