apiVersion: v1
kind: Pod
metadata:
  name: emptydir-memory-10m
  labels:
    app: emptydir-memory-10m 
spec:
  containers:
  - name: emptydir-memory-10m 
    image: sysnet4admin/sleepy
    volumeMounts:
    - mountPath: /emptydir
      name: empty-directory 
  volumes:
  - name: empty-directory 
    emptyDir: 
      medium: Memory
      sizeLimit: "10Mi"
