#Main_Source_From: 
## - https://github.com/kubernetes-sigs/metrics-server

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  k8s-app: metrics-server
resources:
  - apiservice.yaml
  - deployment-notls.yaml
  - rbac.yaml
  - service.yaml
