apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-adapters
spec:
  selector:
    matchLabels:
      app: pod-adapters 
  replicas: 2
  template:
    metadata:
      labels:
        app: pod-adapters 
      annotations:
        prometheus.io/port: "9113"    # added for prometheus scraped 
        prometheus.io/scrape: "true"  # added for prometheus scraped 
    spec:
      containers:
      - name: web-page
        image: nginx 
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf

      - name: adapter
        image: nginx/nginx-prometheus-exporter:0.9.0
        env:
        - name: SCRAPE_URI
          value: http://localhost/stub_status
        ports:
        - containerPort: 9113

      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: default.conf
            path: default.conf
