apiVersion: batch/v1
kind: Job
metadata:
  name: job-curl-fail
spec:
  template:
    spec:
      containers:
      - name: net-tools
        image: sysnet4admin/net-tools
        command: ["curlchk",  "hoon"]
      restartPolicy: Never
