apiVersion: batch/v1
kind: Job
metadata:
  name: job-parallelism
spec:
  parallelism: 3 
  template:
    spec:
      containers:
      - name: net-tools
        image: sysnet4admin/net-tools
        command: ["curlchk",  "nginx"]
      restartPolicy: Never
