apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-w-pvc 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-w-pvc
  template:
    metadata:
      labels:
        app: deploy-w-pvc
    spec:
      containers:
      - name: chk-log 
        image: sysnet4admin/chk-log
        volumeMounts:
        - name: pvc-vol
          mountPath: /audit
      volumes:
      - name: pvc-vol
        persistentVolumeClaim:
          claimName: pvc-dynamic 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-w-pvc
  name: deploy-w-pvc-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy-w-pvc
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: managed-nfs-storage
