apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apy-nginx
  name: apy-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apy-nginx
  template:
    metadata:
      labels:
        app: apy-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
